#ifndef _LCM_MB_Register_Password_
#define _LCM_MB_Register_Password_

/* _____DEFINETIONS__________________________________________________________ */


// Coils Register
enum LCM_DISCRETE_OUTPUT_COILS_REGISTER_FOR_PASSWORD_INDEX
{
    LCM_COIL_PASSWORD_SYSTERM_1,
	LCM_COIL_PASSWORD_SYSTERM_2,
	LCM_COIL_PASSWORD_SYSTERM_3,
	LCM_COIL_PASSWORD_SYSTERM_4,
	LCM_COIL_PASSWORD_SYSTERM_5,
	LCM_COIL_PASSWORD_SYSTERM_6,
	LCM_COIL_PASSWORD_SYSTERM_7,
	LCM_COIL_PASSWORD_SYSTERM_8,
	LCM_COIL_PASSWORD_SYSTERM_9,
	LCM_COIL_PASSWORD_SYSTERM_10
};

enum LCM_DISCRETE_INPUT_CONTACTS_REGISTER_FOR_PASSWORD_INDEX
{
    LCM_DI_PASSWORD_SYSTERM_1,
	LCM_DI_PASSWORD_SYSTERM_2,
	LCM_DI_PASSWORD_SYSTERM_3,
	LCM_DI_PASSWORD_SYSTERM_4,
	LCM_DI_PASSWORD_SYSTERM_5,
	LCM_DI_PASSWORD_SYSTERM_6,
	LCM_DI_PASSWORD_SYSTERM_7,
	LCM_DI_PASSWORD_SYSTERM_8,
	LCM_DI_PASSWORD_SYSTERM_9,
	LCM_DI_PASSWORD_SYSTERM_10
};

enum LCM_HOLDING_REGISTERS_FOR_PASSWORD_INDEX
{
    LCM_HR_PASSWORD_SYSTERM_1,
	LCM_HR_PASSWORD_SYSTERM_2,
	LCM_HR_PASSWORD_SYSTERM_3,
	LCM_HR_PASSWORD_SYSTERM_4,
	LCM_HR_PASSWORD_SYSTERM_5,
	LCM_HR_PASSWORD_SYSTERM_6,
	LCM_HR_PASSWORD_SYSTERM_7,
	LCM_HR_PASSWORD_SYSTERM_8,
	LCM_HR_PASSWORD_SYSTERM_9,
	LCM_HR_PASSWORD_SYSTERM_10
};

enum LCM_INPUT_REGISTERS_FOR_PASSWORD_INDEX
{
    LCM_IR_PASSWORD_SYSTERM_1,
	LCM_IR_PASSWORD_SYSTERM_2,
	LCM_IR_PASSWORD_SYSTERM_3,
	LCM_IR_PASSWORD_SYSTERM_4,
	LCM_IR_PASSWORD_SYSTERM_5,
	LCM_IR_PASSWORD_SYSTERM_6,
	LCM_IR_PASSWORD_SYSTERM_7,
	LCM_IR_PASSWORD_SYSTERM_8,
	LCM_IR_PASSWORD_SYSTERM_9,
	LCM_IR_PASSWORD_SYSTERM_10
};


#endif
